Wait for document ready before doing things
rherwig/franz-5-googlecalendar pull request #4
Opened 2019-02-25 19:01 UTC by cohoe

This came up from discussion in meetfranz/franz#1223. In situations where Google Calendar loads slowly, these two actions (`appendChild` and `addEventListener`) generate exceptions because the document is not ready. I am reasonably certain those exceptions cause any darkmode.css (meetfranz/franz#960) to not be injected (probably related to #3 ). When applying this patch I am able to successfully render Google Calendar with darkmode.

![franz](https://user-images.githubusercontent.com/505621/53361261-5c706400-3905-11e9-8d14-474b2f959deb.PNG)

2019-02-28 19:22 UTC, rherwig requested changes

2019-02-28 19:22 UTC, rherwig commented on webview.js
> +  document.addEventListener("DOMContentLoaded", function(event) {
Please refactor to arrow function.

2019-02-28 19:22 UTC, rherwig commented
Thanks a lot for the PR! The change seems reasonable to me. There is only one small refactoring pending. After that, I am happy to merge.

2019-02-28 19:37 UTC, cohoe commented
Refactor change pushed. Confirmed it does still work.

2019-02-28 19:51 UTC, rherwig approved these changes

2019-02-28 19:51 UTC, merged

2019-02-28 19:51 UTC, rherwig commented
Thanks! Merged.

2019-03-01 16:55 UTC, cohoe commented
@rherwig Do we need to do anything else to get this rolled out upstream?

2019-03-13 18:21 UTC, rherwig commented
@cohoe I am so sorry for the delay! Deployment issue has been created.